# Generated by Django 5.1.2 on 2025-03-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('customer_type', models.CharField(choices=[('Individual', 'Individual'), ('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler')], default='Individual', max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('tailor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('design_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDesign',
            fields=[
                ('custom_design_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], max_length=20)),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.designrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Net Banking', 'Net Banking'), ('Wallet', 'Wallet')], max_length=20)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Refund', 'Refund')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedDesign',
            fields=[
                ('selected_design_id', models.AutoField(primary_key=True, serialize=False)),
                ('selection_date', models.DateField()),
                ('status', models.CharField(choices=[('Selected', 'Selected'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('custom_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.customdesign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myecommerce.product')),
                ('tailor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myecommerce.tailor')),
            ],
        ),
        migrations.CreateModel(
            name='DesignSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.designrequest')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.tailor')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myecommerce.product')),
            ],
        ),
    ]
