# Generated by Django 5.1.2 on 2025-03-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='myecommerce_customer',
        ),
    ]
