# Generated by Django 5.1.2 on 2025-03-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0003_alter_customer_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='CustomerId',
        ),
    ]
