# Generated by Django 5.1.2 on 2025-03-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0006_alter_customer_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler')], db_column='CustomerType', default='Individual', max_length=20),
        ),
    ]
