# Generated by Django 5.1.2 on 2025-03-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0009_remove_customdesign_custom_design_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='design_request_id',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='details',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='designrequest',
            name='CustomerId',
            field=models.ForeignKey(db_column='CustomerId', default=1, on_delete=django.db.models.deletion.CASCADE, to='myecommerce.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designrequest',
            name='DesignRequestID',
            field=models.AutoField(db_column='DesignRequestID', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designrequest',
            name='RequestDate',
            field=models.DateField(db_column='RequestDate', default=-2019),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designrequest',
            name='Details',
            field=models.TextField(blank=True, db_column='Details', null=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='Status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_column='Status', default='pending', max_length=20),
            preserve_default=False,
        ),
    ]
