# Generated by Django 5.1.2 on 2025-03-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0010_remove_designrequest_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CustomerId',
            field=models.AutoField(db_column='CustomerId', primary_key=True, serialize=False),
        ),
    ]
