# Generated by Django 5.1.2 on 2025-03-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0011_alter_customer_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.CASCADE, to='myecommerce.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(db_column='OrderDate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(db_column='OrderID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
