# Generated by Django 5.1.2 on 2025-03-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0012_alter_order_customer_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='myecommerce.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(db_column='PaymentDate'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(db_column='PaymentID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Net Banking', 'Net Banking'), ('Wallet', 'Wallet')], db_column='PaymentMethod', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Refund', 'Refund')], db_column='Status', max_length=20),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='Payment',
        ),
    ]
