# Generated by Django 5.1.2 on 2025-03-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0013_alter_payment_amount_alter_payment_order_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='selecteddesign',
            table='selecteddesign',
        ),
    ]
