# Generated by Django 5.1.2 on 2025-03-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0015_alter_selecteddesign_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='tailor_id',
            field=models.AutoField(db_column='TailorID', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='tailor',
            table='myecommerce_tailor',
        ),
    ]
