# Generated by Django 5.1.2 on 2025-03-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0016_alter_tailor_tailor_id_alter_tailor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tailor',
            table='tailor',
        ),
    ]
