# Generated by Django 5.1.2 on 2025-03-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0019_rename_wishlist_id_wishlist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Dupatta', 'Dupatta'), ('Blouses', 'Blouses'), ('Kurti', 'Kurti'), ('Choli', 'Choli'), ('Kurta Sets', 'Kurta Sets')], max_length=100),
        ),
    ]
