# Generated by Django 5.1.2 on 2025-03-30 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0020_product_image_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='customer', 
                to=settings.AUTH_USER_MODEL, 
                null=True  # Allow it to be nullable if you're handling it manually
            ),
        ),
    ]

