# Generated by Django 5.1.2 on 2025-03-31 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0023_remove_cartitem_id_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='id',
            new_name='wishlist_id',
        ),
    ]
