# Generated by Django 5.1.2 on 2025-03-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0024_rename_id_wishlist_wishlist_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='myecommerce_cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='myecommere_cartitem',
        ),
    ]
