# Generated by Django 5.1.2 on 2025-03-31 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0025_alter_cart_table_alter_cartitem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='myecommerce_cartitem',
        ),
    ]
