# Generated by Django 5.1.2 on 2025-04-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0028_alter_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
