# Generated by Django 5.1.2 on 2025-04-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0031_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
