# Generated by Django 5.1.2 on 2025-04-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0032_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist_images/'),
        ),
    ]
